name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  schedule:
    - cron: "30 10 * * 4"
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_CONTAINER_NAME: cloudflared
  DOCKER_TARGET_PLATFORM: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ !github.event.act }}

      - name: Get latest Cloudflared Version
        id: cloudflared
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: cloudflare
          repo: cloudflared
          token: ${{ secrets.GITHUB_TOKEN }}
          excludes: prerelease, draft

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
          echo "::set-output name=tag::${{ steps.cloudflared.outputs.release }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          build-args: CLOUDFLARED_VERSION=${{ steps.cloudflared.outputs.release }}
          tags: |
            ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ steps.prepare.outputs.tag }}
            ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:latest