name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  schedule:
    - cron: "30 10 * * 4"
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_CONTAINER_NAME: cloudflared
  DOCKER_TARGET_PLATFORM: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ !github.event.act }}

      - name: Get latest Cloudflared Version
        id: cloudflared-version
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: cloudflare
          repo: cloudflared
          token: ${{ secrets.GITHUB_TOKEN }}
          excludes: prerelease, draft

      - name: Prepare
        id: prepare
        run: |
          echo "docker_platform=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_ENV
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ steps.cloudflared-version.outputs.release }}" >> $GITHUB_ENV

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Print Hadolint lint results
        run: echo 'HADOLINT LINT RESULTS => ${{ env.HADOLINT_RESULTS }}'
        
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          build-args: CLOUDFLARED_VERSION=${{ env.IMAGE_TAG }}
          tags: |
            ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:latest
