name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  schedule:
    - cron: "30 10 * * 4"
  workflow_dispatch:
    inputs:
      force:
        description: Build the image even if it already exists
        required: false
        default: false
        type: boolean

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest cloudflared version
        id: cloudflared-version
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: cloudflare
          repo: cloudflared
          token: ${{ secrets.GITHUB_TOKEN }}
          excludes: prerelease, draft

      - name: Prepare
        run: |
          echo "TARGET_IMAGE_TAG=${{ steps.cloudflared-version.outputs.release }}" >> $GITHUB_ENV

  build:
    needs: initialize
    uses: ./.github/workflows/build-docker-image.yml
    with:
      target_tag: ${{ env.TARGET_IMAGE_TAG }}
      build_args: CLOUDFLARED_VERSION=${{ env.TARGET_IMAGE_TAG }}
      force: ${{ inputs.force }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}